# This file was generated by GoReleaser. DO NOT EDIT.
cask "teamvault-cli" do
  version "5.7.0"

  on_macos do
    on_intel do
      sha256 "c85c8f2bb64fdd11704da4bdc6d13860862d35ca4ad05688256e8956120e671a"
      url "https://github.com/Seibert-Data/teamvault-cli/releases/download/v#{version}/teamvault-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f03d10808f716d5ad5666f697ef4c9d5741f175420400f5982ea3bbfc9aa406"
      url "https://github.com/Seibert-Data/teamvault-cli/releases/download/v#{version}/teamvault-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d77e9218c49bb34f9434dee92b889a9f2a22f7d61893b4b3c22a496ce8daee68"
      url "https://github.com/Seibert-Data/teamvault-cli/releases/download/v#{version}/teamvault-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "baa85b6d1ec9c214840b2617f1376c4978175d75fcd6670ab74ddedfec6f6b75"
      url "https://github.com/Seibert-Data/teamvault-cli/releases/download/v#{version}/teamvault-cli_linux_arm64.tar.gz"
    end
  end

  name "teamvault-cli"
  desc "Read secrets from TeamVault (passwords, usernames, URLs, files) by lookup key"
  homepage "https://github.com/Seibert-Data/teamvault-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "teamvault-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/teamvault-cli"]
  end

  # No zap stanza required

end
