# This file was generated by GoReleaser. DO NOT EDIT.
cask "teamvault-cli" do
  version "5.8.0"

  on_macos do
    on_intel do
      sha256 "f9b7b2a352bd233eddca69712fe22ec0d1d340c955010bc55eef0fbe2a7bf156"
      url "https://github.com/Seibert-Data/teamvault-cli/releases/download/v#{version}/teamvault-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a680bac36dfabf8093066ec78337421c0821b9088243e57b213fe152ba5cdaa"
      url "https://github.com/Seibert-Data/teamvault-cli/releases/download/v#{version}/teamvault-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "139e93ce8ac54c819a982c5a01246ce3ea1faf7fcb327e2f199661bb94344add"
      url "https://github.com/Seibert-Data/teamvault-cli/releases/download/v#{version}/teamvault-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e4e7e0612e51bae97cb57ff2089cae5c4affa95e40c39118c2b75447ff3931b2"
      url "https://github.com/Seibert-Data/teamvault-cli/releases/download/v#{version}/teamvault-cli_linux_arm64.tar.gz"
    end
  end

  name "teamvault-cli"
  desc "Read secrets from TeamVault (passwords, usernames, URLs, files) by lookup key"
  homepage "https://github.com/Seibert-Data/teamvault-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "teamvault-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/teamvault-cli"]
  end

  # No zap stanza required

end
