# This file was generated by GoReleaser. DO NOT EDIT.
cask "teamvault-cli" do
  version "5.5.1"

  on_macos do
    on_intel do
      sha256 "10224b0f74c865dd31d46b2fccae6da7795967315b3d50971e55dcef4c2622ca"
      url "https://github.com/Seibert-Data/teamvault-cli/releases/download/v#{version}/teamvault-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff2422cb239c6d3c15537b98b86e48940dd3b3a2f9a2c536cbd0912825785205"
      url "https://github.com/Seibert-Data/teamvault-cli/releases/download/v#{version}/teamvault-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "26d273a07f2f64b9bba668acc2ec279bbcc06bae8ec3622959feffa231ed72f6"
      url "https://github.com/Seibert-Data/teamvault-cli/releases/download/v#{version}/teamvault-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c2d5038a5ca742ea6ac0feb6ba718c75d49c1166d2f781d43345dbbadb8dda43"
      url "https://github.com/Seibert-Data/teamvault-cli/releases/download/v#{version}/teamvault-cli_linux_arm64.tar.gz"
    end
  end

  name "teamvault-cli"
  desc "Read secrets from TeamVault (passwords, usernames, URLs, files) by lookup key"
  homepage "https://github.com/Seibert-Data/teamvault-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "teamvault-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/teamvault-cli"]
  end

  # No zap stanza required

end
